const NOT_FOUND = 'Not Found';
const UNAUTHORIZED = 'Unauthorized';
const BAD_REQUEST = 'Bad Request';
const CONFLICT = 'Conflict';
const INTERNAL_SERVER_ERROR = 'Internal Server Error';
const NOT_FOUND_CODE = 404;
const UNAUTHORIZED_CODE = 401;
const BAD_REQUEST_CODE = 400;
const CONFLICT_CODE = 409;
const INTERNAL_SERVER_ERROR_CODE = 500;
const OK_CODE = 200;
const CREATED_CODE = 201;
const NO_CONTENT_CODE = 204;

module.exports = {
  NOT_FOUND,
  UNAUTHORIZED,
  BAD_REQUEST,
  CONFLICT,
  INTERNAL_SERVER_ERROR,
  NOT_FOUND_CODE,
  UNAUTHORIZED_CODE,
  BAD_REQUEST_CODE,
  CONFLICT_CODE,
  INTERNAL_SERVER_ERROR_CODE,
  OK_CODE,
  CREATED_CODE,
  NO_CONTENT_CODE,
};
